# Python para el análisis de datos -  UNAV 2020-2021
---

# Proyecto Final

Este año, la nota final se evaluará teniendo en cuenta un pequeño proyecto.
Este proyecto se realizará por parejas. Estas parejas no podrán haber estudiado juntos o estar en el mismo equipo a nivel laboral.
 

El proyecto consistirá en ser capaces de bajar la cotización de un par de monedas, un ejemplo de cotizaciones en Kraken:
https://www.kraken.com/es-es/prices?quote=EUR

Después de bajarlas, será necesario hacer una gráfica del movimiento que ha tenido.

Además, se hará una gráfica de la media móvil:
https://www.rankia.com/diccionario/trading/medias-moviles

La entrega final consistirá como mínimo en:

- Una memoria, la memoria será el contenido principal de la entrega.
- Código, excluida cualquier librería adicional. Este código será material auxiliar para la corrección pero será obligado que también esté presente en la entrega.

Puntos mínimos:

- Lectura y representación del movimiento del par de monedas - Máximo (4 puntos)
    - Descargar datos. Máximo (2 puntos)  
        - Utilizando la librería Kraken (2 puntos).
          https://github.com/veox/python3-krakenex
        - Utilizando descarga directa a través de Pandas (1 punto).
          https://drive.google.com/uc?id=1eQsiD8Z8wEt1mx9VICzCmIEQufWjaUD-
        - Descargar directamente y utilizar el csv en local (0 puntos).
    - Graficar cotizaciones. Máximo (2 puntos).
        - Graficar el par ETH/USDT  (1 punto).
        - Input de usuario que permita graficar cualquier cotización o una a elegir en el menú (2 puntos).

- Indicadores técnicos. Máximo (3 puntos).
    - Calcular el Media Móvil y graficarla (1 puntos).
    - Calcular el RSI y graficarlo (1 puntos).
    - Graficar el Media Móvil junto con la cotización del par calculado (1 punto).

- Estructuración. Máximo (1 punto)
    - Funciones (0,5 puntos)
    - Utilización de clases (0,5 puntos)
    - Manejo de errores y excepciones (0,5 puntos)

- Memoria obligatoria. Máximo (2 puntos).
    - Descripción de cómo se ha afrontado el proyecto y por qué.
    - Descripción detallada de cada uno de los puntos que se evalúan.
    - Descripción de la estructura del código y estructura de ficheros.
    - Descripción de la forma de ejecución del código.
    - Pantallazos de todo Aquel punto que requiera algún tipo de visualización.
    - NADA QUE NO SE PUEDA ENCONTRAR DESCRITO O MOSTRADO EN LA MEMORIA SERÁ EVALUADO, AUNQUE ESTÉ REALIZADO EN EL CÓDIGO.

- Puntación Extra. Máximo (1 punto)
    - Testeo y cobertura (unit-testing, integration-testing) 0,25 puntos
    - Facilitar los mecanismos para la reproducción del entorno virtual (ya sea con Poetry, Pipenv o pip) 0,25 puntos
    - Distribución del proyecto a través de PyPi o una plataforma PaaS (AWS, Heroku, etc) 0,25 puntos

La plazo de entrega finalizará el 29 de diciembre a las 23:59.

In [1]:
%reload_ext autoreload

%autoreload 2

In [2]:
from src import kraken_functions
from src.libraries import *
from src.display_UI import metricas,divisa,intervalos,button, display_criptos, output, button, on_button_clicked,date

In [3]:

pd.set_option('display.max_columns', None)

In [4]:
display(divisa)
display(button, output)
button.on_click(on_button_clicked)
display(intervalos)
display(date)

RadioButtons(description='Seleccione el tipo de divisa', options=('EUR', 'USD'), style=DescriptionStyle(descri…

Button(description='Click Me!', style=ButtonStyle())

Output()

Dropdown(description='Seleccione intervalo:', index=1, options=(1, 5, 15, 30, 60, 240, 1440, 10080, 21600), st…

DatePicker(value=None, description='Pick a Date', step=1, style=DescriptionStyle(description_width='initial'))

In [5]:
date.value

datetime.date(2022, 11, 25)

In [21]:
date="2022-09-30"
aux=dt.datetime.strptime(date,"%Y-%m-%d")
inicio=dt.datetime.timestamp(aux)

1664488800.0

In [24]:
import krakenex
pair = 'XETHZEUR'
k = krakenex.API()
ret = k.query_public('OHLC', data = {'pair': pair, 'since': inicio})

In [27]:
intervalo=5
bars = ret['result'][pair]
ohlc = pd.DataFrame(ret['result'][pair])
ohlc.columns = [
                'time', 'open', 'high', 'low', 'close',
                'vwap', 'volume', 'count',
            ]
ohlc['dtime'] = pd.to_datetime(ohlc.time, unit='s')
ohlc.sort_values('dtime', ascending=False, inplace=True)
ohlc.set_index('dtime', inplace=True)
freq = str(interval) + 'T' if False else str(-interval) + 'T'
ohlc.index.freq = freq

# dtypes
for col in ['open', 'high', 'low', 'close', 'vwap', 'volume']:
    ohlc.loc[:, col] = ohlc[col].astype(float)

              0        1        2        3        4        5            6   7
0    1668146580  1242.60  1243.17  1241.58  1241.98  1243.11  73.54455718  11
1    1668146640  1242.99  1242.99  1242.05  1242.05  1242.91   0.52497664   4
2    1668146700  1241.80  1242.96  1241.80  1242.96  1242.03   0.04866392   2
3    1668146760  1242.57  1243.88  1242.12  1243.88  1242.20   7.89656941  10
4    1668146820  1242.05  1242.05  1241.83  1241.83  1241.83   1.24252095   3
..          ...      ...      ...      ...      ...      ...          ...  ..
715  1668189480  1232.76  1233.01  1231.60  1231.82  1232.90   1.04398316   7
716  1668189540  1231.37  1231.37  1230.57  1231.30  1230.82   9.59809726  10
717  1668189600  1229.98  1234.24  1229.50  1234.24  1229.91  17.95967726  20
718  1668189660  1235.25  1239.00  1235.25  1237.52  1236.90  10.96411372  19
719  1668189720  1236.85  1236.85  1236.71  1236.71  1236.79   2.60718760   3

[720 rows x 8 columns]

In [22]:
data,_=kraken_functions.recoger_datos(pair_list[pair.value][0],inicio)

c:\Users\javca\anaconda3\envs\Unav\lib\site-packages\pykrakenapi\pykrakenapi.py:607: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  ohlc.loc[:, col] = ohlc[col].astype(float)

In [23]:
data

,time,open,high,low,close,vwap,volume,count
dtime,,,,,,,,
2022-11-11 17:57:00,1668189420,4.023,4.023,4.023,4.023,0.000,0.000000,0
2022-11-11 17:56:00,1668189360,4.023,4.023,4.023,4.023,0.000,0.000000,0
2022-11-11 17:55:00,1668189300,4.023,4.023,4.023,4.023,0.000,0.000000,0
2022-11-11 17:54:00,1668189240,4.023,4.023,4.023,4.023,0.000,0.000000,0
2022-11-11 17:53:00,1668189180,4.023,4.023,4.023,4.023,0.000,0.000000,0
...,...,...,...,...,...,...,...,...
2022-11-11 06:02:00,1668146520,4.145,4.145,4.145,4.145,0.000,0.000000,0
2022-11-11 06:01:00,1668146460,4.145,4.145,4.145,4.145,0.000,0.000000,0
2022-11-11 06:00:00,1668146400,4.136,4.145,4.136,4.145,4.141,16.978477,2
2022-11-11 05:59:00,1668146340,4.116,4.116,4.116,4.116,0.000,0.000000,0
2022-11-11 05:58:00,1668146280,4.116,4.116,4.116,4.116,0.000,0.000000,0